name: github action workflow demo
on:
  workflow_dispatch:
jobs:
  GithubActionWorkflowDemo:
    runs-on: ubuntu-24.04
    steps:
      - name: find ip address

        run: |
          hostname -I
          echo "${var1}"
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Build Project
        run: mvn clean install
      - name: list directory
        run: ls -al